### ISSUE TITLE
add threshold to key

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/match-sorter#25]
Just like we have a `threshold` in general options, each key should be able to specify a `threshold`.

```javascript
matchSorter(objList, 'g', {
  keys: ['name', {threshold: matchSorter.rankings.ACRONYM, key: 'color'}],
})
```

This would mean that an item would have to have a ranking of `ACRONYM` with `color` or greater to be included in the final results. However, if an item did have a ranking with `name` that would still be included even if it didn't match well enough with `key`.

**Comment by kentcdodds** [comment]
This is sorted with the `maxRanking` and `minRanking` properties.

**Comment by bacancykrina** [comment]
Hello, 

```
{
                      Header: "Location Name",
                      accessor: "name",
                      filterMethod: (filter, rows) =>
                          matchSorter(rows, filter.value, {keys: ["name"]}, {maxRanking: rankings.CASE_SENSITIVE_EQUAL}),
                      filterAll: true
                    }
```
This is not filtering case sensitive data. Am i missing anything? 
Need Help !!

**Comment by kentcdodds** [comment]
Could you perhaps make an example of the issue you're having here: https://codesandbox.io/s/wyk856yo48

**Comment by tikotzky** [comment]
Hey, I'm having trouble figuring how to use `minRanking` and `maxRanking` in place of a threshold on each key. I'm trying to have the general threshold be set to `CONTAINS`, but specific keys should not match unless they're at least `STARTS_WITH`.

I made a sandbox to test with here https://codesandbox.io/s/l7q740yr1l
In the linked sandbox the behavior I'm aiming for, is that if you search for `ed` it would only return `{"name":"Jen","color":"Red"}`. 
Right now it's also returning `{"name":"Fred","color":"Orange"}` since "Fr**ed**" is matching. I'm trying to have it only match the name if the name `STARTS_WITH` `ed`.

Is this possible to accomplish using `minRanking` and `maxRanking`?

Thanks in advance...

**Comment by kentcdodds** [comment]
Hmmm... I don't believe this is possible. Feel free to open a PR.

**Comment by tikotzky** [comment]
I created PR https://github.com/kentcdodds/match-sorter/pull/50

Let me know if you have any feedback or changes.
